In [1]:
import os
import sys
import numpy as np
import pandas as pd 

sys.path.insert(0, '../')
from scripts.tracking import TeamTracking

In [2]:
data_directory = '../data/SecondSpectrum'
file = 'g2312183_SecondSpectrum_tracking-produced.jsonl'
match_tracking_path = os.path.join(data_directory, file)

# < 20s
df_unstructured_tracking = pd.read_json(match_tracking_path, lines = True)

In [3]:
df_unstructured_tracking.head()

,period,frameIdx,gameClock,wallClock,homePlayers,awayPlayers,ball,live,lastTouch
0,1,0,0.00,1670162509680,[{'playerId': '0746befc-a701-4b33-8faf-b3ccccc...,[{'playerId': '28297289-4265-4a74-bcbc-b1e4320...,"{'xyz': [-0.28, 0.09, 0.29], 'speed': 9.29}",False,home
1,1,1,0.04,1670162509720,[{'playerId': '0746befc-a701-4b33-8faf-b3ccccc...,[{'playerId': '28297289-4265-4a74-bcbc-b1e4320...,"{'xyz': [-0.7000000000000001, 0.21, 0.29], 'sp...",True,home
2,1,2,0.08,1670162509760,[{'playerId': '0746befc-a701-4b33-8faf-b3ccccc...,[{'playerId': '28297289-4265-4a74-bcbc-b1e4320...,"{'xyz': [-1.1, 0.32, 0.29], 'speed': 8.97}",True,home
3,1,3,0.12,1670162509800,[{'playerId': '0746befc-a701-4b33-8faf-b3ccccc...,[{'playerId': '28297289-4265-4a74-bcbc-b1e4320...,"{'xyz': [-1.5, 0.44, 0.29], 'speed': 8.81}",True,home
4,1,4,0.16,1670162509840,[{'playerId': '0746befc-a701-4b33-8faf-b3ccccc...,[{'playerId': '28297289-4265-4a74-bcbc-b1e4320...,"{'xyz': [-1.9100000000000001, 0.52, 0.29], 'sp...",True,home

In [4]:
# Traitement de 1,5M de lignes en < 3s
HomeTracking = TeamTracking(df_unstructured_tracking=df_unstructured_tracking)
df_tracking_head = HomeTracking.df_tracking

In [5]:
HomeTracking.calculate_acceleration()

,period,frameIdx,gameClock,wallClock,live,lastTouch,optaId,speed,x,y,acceleration
0,1,0,0.0,1670162509680,False,home,192194,0.00,-10.10,1.68,NaN
0,1,0,0.0,1670162509680,False,home,174349,0.00,-0.15,-27.56,NaN
0,1,0,0.0,1670162509680,False,home,243637,0.00,-0.28,20.76,NaN
0,1,0,0.0,1670162509680,False,home,96385,0.00,-4.08,9.55,NaN
0,1,0,0.0,1670162509680,False,home,459038,0.00,-4.85,-11.14,NaN
...,...,...,...,...,...,...,...,...,...,...,...
143055,2,143055,2893.8,1670169209400,False,away,463306,0.83,-40.54,-2.76,0.0
143055,2,143055,2893.8,1670169209400,False,away,175128,1.05,-37.53,5.69,0.0
143055,2,143055,2893.8,1670169209400,False,away,96535,1.49,-11.47,-29.41,0.0
143055,2,143055,2893.8,1670169209400,False,away,434287,0.94,-3.30,-5.70,0.0
143055,2,143055,2893.8,1670169209400,False,away,472359,0.35,-4.12,-17.21,0.0

In [6]:
HomeTracking.calculate_metabolic_cost()

,period,frameIdx,gameClock,wallClock,live,lastTouch,optaId,speed,x,y,acceleration,metabolic_cost
0,1,0,0.0,1670162509680,False,home,192194,0.00,-10.10,1.68,NaN,NaN
0,1,0,0.0,1670162509680,False,home,174349,0.00,-0.15,-27.56,NaN,NaN
0,1,0,0.0,1670162509680,False,home,243637,0.00,-0.28,20.76,NaN,NaN
0,1,0,0.0,1670162509680,False,home,96385,0.00,-4.08,9.55,NaN,NaN
0,1,0,0.0,1670162509680,False,home,459038,0.00,-4.85,-11.14,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
143055,2,143055,2893.8,1670169209400,False,away,463306,0.83,-40.54,-2.76,0.0,3.601556
143055,2,143055,2893.8,1670169209400,False,away,175128,1.05,-37.53,5.69,0.0,3.601556
143055,2,143055,2893.8,1670169209400,False,away,96535,1.49,-11.47,-29.41,0.0,3.601556
143055,2,143055,2893.8,1670169209400,False,away,434287,0.94,-3.30,-5.70,0.0,3.601556
143055,2,143055,2893.8,1670169209400,False,away,472359,0.35,-4.12,-17.21,0.0,3.601556